### PR TITLE
Add conv2d function

### PR DESCRIPTION
**Pull request by odashi**
This pull-request adds the new function `conv2d`, convolution function between 2 (`input` and `filter`) images.
- Usage:
```c++
// Using `Node` instead of `Tensor` is also allowed.
Tensor input = functions::input(Shape({128, 128, 3}, 64), ...);
Tensor filter = functions::input({3, 3, 3, 20}, ...);
Tensor output = functions::conv2d(
    input, filter,
    0, 0,  // paddings (1st-dim, 2nd-dim)
    1, 1,  // strides (1st-dim, 2nd-dim)
    1, 1);  // dilation factors (1st-dim, 2nd-dim)
// `output` is of Shape({126, 126, 20}, 64)
```
- Input is of `Shape({i_height, i_width, i_channels}, minibatch)`
- Filter is of `Shape({f_height, f_width, i_channels, o_channels}, minibatch)`
- Output is of `Shape({o_height, o_width, o_channels}, minibatch)`
- Swapping `*_height` and `*_width` is also allowed.
- The minibatch broadcasting rule (between `input` and `filter`) is identical with other binary operators such as `operator+`.

`o_height/width` is calculated as:
- `o_height = i_height - f_height + 1`
- `o_width = i_width - f_width + 1`

This pull-request implements only the simplest version of convolution functions which has no hyper-parameters. I am planning to add some additional options such as *padding*, *stride* and *dilation* after this pull-request.

Related issues: #35.

**EDIT**: This branch is updated to implement also *padding*, *stride*, *dilation* options.
`o_height/width` with these options are calculated as:
- `o_height = (i_height + 2 * padding - (f_height - 1) * dilation + 1) / stride + 1`
- `o_width = (i_width + 2 * padding - (f_height - 1) * dilation + 1) / stride + 1`

This branch adds a dependency to **cuDNN** and changes the minimum supported version of CUDA to 8.0.

### CODE REVIEW

**Comment by odashi** [comment]
Related to: #35.

**Comment by vbkaisetsu** [comment]
Could you add tests that convolute floating point matrices to guarantee precision and internal data type?
Additionally, could you add convolution test of large matrices such as 256x256x3 images for actual image processing?

**Comment by odashi** [comment]
- Tests for floating point numbers
All tests are already of floating point numbers (which are tested using 4-ULPs criteria), and `conv2d` supports only `float` type for now.

**Comment by odashi** [comment]
- Testing large images
  m,,,,

**Comment by odashi** [comment]
- Testing with large images
I guess very large convolutions should not be included if they don't have any corner cases because they impose a large burden that affects running time of tests.

**Comment by odashi** [comment]
I am planning to add a test with shape `[224, 224, 3]` and `[3, 3, 3, 64]` which is used as the first layer of [VGG16](https://arxiv.org/abs/1409.1556) model, and will test the actual increase of running time. This example requires *padding* to generate output layers with the same size as the input, and so I will also implement some pending options (described in the first comment) together with this test.

**Comment by odashi** [comment]
I implemented all features and tests calculating the first layer of VGG16, and confirmed that the increase of running time of tests is not large.

**Review by vbkaisetsu — APPROVED** [review]
Okay. LGTM.

**Pull request merged**
