### PR TITLE
Support Eigen backend

### PR DESCRIPTION
**Pull request by odashi**
Issues: #68, #119.
This pull request adds a CPU device class that uses Eigen library as a backend.

### CODE REVIEW

**Review by chantera — DISMISSED** [review]
LGTM. I tried the MNIST example using Eigen and it works well.

**Review by vbkaisetsu — COMMENTED** [review]
I think it's better to add an option to enable (or disable) `-march=native` flag.

**Comment by odashi** [comment]
Add `-march=native` compiler option to CMakeLists.txt.

**Review by vbkaisetsu — APPROVED** [review]
LGTM

**Pull request merged**
