### PR TITLE
Add pown device functions.

### PR DESCRIPTION
**Pull request by odashi**
This pull-request adds the *power-of-integer* functions `Device::pown_fw/bw`, `operators::PowN`, and `functions::pown<Var>`.

### CODE REVIEW

**Comment by odashi** [comment]
Related to: #26.

**Review by vbkaisetsu — DISMISSED** [review]
LGTM.

**Review by chantera — DISMISSED** [review]
LGTM.

**Comment by odashi** [comment]
This branch uses `std::to_string()` which were replaced to `primitiv::string_utils::to_string()` by #144. I will fix corresponding code after merging that branch.

**Review by vbkaisetsu — APPROVED** [review]
LGTM.

**Pull request merged**
